name: Tests

on: [pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.0, nightly]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@2.25.2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install Dependencies
        run: composer install --ignore-platform-reqs

      - name: Run Tests
        run: composer test